package plugin;

import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.PlayerDeathEvent;

/**
 * WMY/Kobun language polish for Minecraft vanilla death messages.
 *
 * Some death messages are generated by Minecraft/Spigot itself, not by TreasureRun's i18n YAML.
 * This listener only rewrites visible death messages when the player selected wmy.
 */
public class WmyDeathMessageListener implements Listener {

  private final TreasureRunMultiChestPlugin plugin;

  public WmyDeathMessageListener(TreasureRunMultiChestPlugin plugin) {
    this.plugin = plugin;
  }

  @EventHandler
  public void onPlayerDeath(PlayerDeathEvent event) {
    Player player = event.getEntity();
    if (player == null) return;

    String lang = "ja";
    try {
      if (plugin.getPlayerLanguageStore() != null) {
        lang = plugin.getPlayerLanguageStore().getLang(player, "ja");
      }
    } catch (Throwable ignored) {
      lang = "ja";
    }

    if (!"wmy".equalsIgnoreCase(lang)) return;

    String raw = event.getDeathMessage();
    if (raw == null) return;

    String name = player.getName();

    // Japanese Minecraft message example:
    // flowmariは花火の爆発に巻き込まれた
    // English Minecraft message examples may include firework/fireworks.
    if (raw.contains("花火") || raw.toLowerCase().contains("firework")) {
      event.setDeathMessage(ChatColor.GRAY + name + "は花火の爆ぜに巻かれ、あへなく倒れにけり。");
      return;
    }

    // Very small generic WMY fallback only for selected WMY players.
    // Do not over-localize all death causes yet; keep non-firework deaths readable.
    if (raw.contains("爆発") || raw.toLowerCase().contains("explosion")) {
      event.setDeathMessage(ChatColor.GRAY + name + "は爆ぜの災ひに遭ひ、あへなく倒れにけり。");
    }
  }
}
