name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      - name: Install ripgrep (rg)
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Make check_keys executable
        run: chmod +x ./check_keys.sh

      - name: Validate i18n keys
        run: ./check_keys.sh

      - name: Build (shadowJar)
        run: ./gradlew clean shadowJar
